#!/usr/bin/env python
"""git-pr: fetch a pull request

git pr NR
git pr NR0 NR1 NR2
git pr NR0 NR1 NR2 -args -to -git-fetch

Adds a new branch "pr/NR"

"""

from __future__ import print_function
import subprocess
import sys

if len(sys.argv) < 2:
    print("Usage: git-pr NR")
    print("Usage: git-pr NR0 NR1 NR2 NR3")
    print("Usage: git-pr NR0 NR1 NR2 -args -to -git-fetch")
    sys.exit(-1)

opts = [arg for arg in sys.argv[1:] if arg.startswith('-')]
nrs = [int(arg) for arg in sys.argv[1:] if not arg.startswith('-')]

for i, nr in enumerate(nrs):
    print("Fetching PR #{0} into branch 'pr/{0}'".format(nr))
    cmd = "git checkout master"
    out = subprocess.check_output(cmd.split())

    cmd = "git fetch --force origin pull/{0}/head:pr/{0}".format(nr)
    out = subprocess.check_output(cmd.split() + opts)

    if i != len(nrs) - 1 and not out.endswith('\n'):
        print()

# Switch to last branch checked out
cmd = f"git checkout pr/{nr}"
out = subprocess.check_output(cmd.split())
