#!/bin/bash

main=$(git branch -l master main | sed 's/^* //' | xargs)
git checkout -q $main &&
  git for-each-ref refs/heads/ "--format=%(refname:short)" |
  while read branch; do
    ancestor=$(git merge-base $main $branch) &&
      [[ $(git cherry $main $(git commit-tree $(git rev-parse $branch^{tree}) -p $ancestor -m _)) == "-"* ]] &&
      git branch -D $branch
  done
